// <auto-generated />
using Beca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Beca.Migrations
{
    [DbContext(typeof(BecaContext))]
    [Migration("20180330190923_[Segunda-Migracion]")]
    partial class SegundaMigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Beca.Models.Encuesta", b =>
                {
                    b.Property<int>("EncuestaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<bool>("Chequeado");

                    b.Property<int>("Dni_Libreta");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Localidad")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Pregunta_Aumento_Transporte")
                        .IsRequired();

                    b.Property<string>("Pregunta_Beca_Transporte")
                        .IsRequired();

                    b.Property<string>("Pregunta_Boleto_Edu")
                        .IsRequired();

                    b.Property<string>("Pregunta_Comentarios")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Pregunta_Politica_Iniciativas")
                        .IsRequired();

                    b.Property<string>("Pregunta_Politica_Permanencia")
                        .IsRequired();

                    b.Property<string>("Telefono")
                        .IsRequired();

                    b.HasKey("EncuestaID");

                    b.ToTable("Encuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
